### ISSUE TITLE
Firebase Consistency

### ISSUE THREAD

**Issue by AndrewElvisDeng** [OlimjonNematov/SummerHacks2020#7]
Testing on iOS and Android
Authentication portion of firebase is consistent with registration on devices, but not consistent with the Database tab:
• I've deleted User ZDhsmuK7wfN4TCyTkLvEx0oK3Kj2 from Authentication but it's still in Database, along with many other deleted users.
• User TU1HvXmUycNXu14tha7IbVRVIty2 is in Authentication but not in Database.

tl;dr: Users aren't consistent with user documents

**Comment by OlimjonNematov** [comment]
i created both accounts and it seemed to work fine. Did you make sure that u entered all fields (first, last name etc..)

**Comment by AndrewElvisDeng** [comment]
Yeah, I filled out all the fields.
